[workspace]
resolver = "2"
members = ["mods/pak-natives"]

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "packed"
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
